[package]
name = "blog_os"
version = "0.1.0"
authors = ["ATAROY <atanu.roy@barco.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.8"